name: Docker build and push

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: ['x86', 'arm']
        tls: ['openssl', 'gnutls']
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.1.0
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/${{ matrix.arch }}
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/grab-base:${{ matrix.tls }}
        build-args: TLSTYPE=${{ matrix.tls }}